### ISSUE TITLE
Intellij prompts about files changed in disk

### ISSUE THREAD

**Issue by martskins** [Ruin0x11/intellij-lsp-server#68] opened 2018-07-17 04:21 UTC
So I just installed this and it works **great**!

I'm having one small issue though, I'm using neovim + intellij (on OSx) and what I currently do to start working on a project is open intellij first, so it exposes the LSP server, and then open neovim.
All works great (completion and all), except after a few editions intellij will dissappear (but keep running) but ask me constantly about a changed file in disk.

I saw that the README states that editing in both IDEA and editor is not supported, but I'm not sure how to overcome this. Can the lsp server be run without opening intellij by itself? Is there some kind of headless mode I'm missing?

Any help is greatly appreciated.

**Comment by Ruin0x11** [comment] 2018-07-17 04:48
The file changed dialog seems to be a duplicate of #39. As for headless, I believe there is a headless command line runner that can be implemented (`ApplicationStarterEx`). I'm not sure how this would interact with IntelliJ internals since much of it depends on the UI thread being available. However, since the main window can be hidden via an LSP command anyway, it might actually be feasible somehow if all the headless mode does is hide the window.

**Comment by martskins** [comment] 2018-07-17 16:48
so if I understood #39 correctly there is currently no solution or workaround for this other than resolving the conflict by picking "Load FS Changes". Or is there something that can be done to make this less painful? Should we maybe open a feature request in intellij? 

In any case this is amazing, thank you!

Also, feel free to close this issue, I'll keep an eye on #39.

**Comment by Ruin0x11** [comment] 2018-07-17 17:17
There isn't an easy one as far as I can tell. At minimum a lot of reflection would be needed, and I'm not even sure some of what needs to be done is possible currently (subclassing a package-private class and passing it to a test-only method). It might be better to ask IntelliJ if this specific use case can be supported in the SDK at least.

**Closed** 2018-07-17 17:17 UTC
